project_name: duncan
release:
  github:
    owner: betterdoctor
    name: duncan
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X github.com/betterdoctor/duncan/cmd.Version={{.Tag}}
  binary: duncan
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
